/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ApiError: typeof import('./src/components/ui/apiError.vue')['default']
    Barcode: typeof import('./src/components/ui/barcode.vue')['default']
    Breadcrumb: typeof import('./src/components/layout/Breadcrumb.vue')['default']
    Button: typeof import('./src/components/ui/button.vue')['default']
    CurrencyInput: typeof import('./src/components/ui/currencyInput.vue')['default']
    Dropdown: typeof import('./src/components/ui/dropdown.vue')['default']
    ErrorModal: typeof import('./src/components/ui/modals/errorModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputError: typeof import('./src/components/ui/inputError.vue')['default']
    LoadingComponent: typeof import('./src/components/ui/loadingComponent.vue')['default']
    MasterLayout: typeof import('./src/components/layout/MasterLayout.vue')['default']
    RedCaution: typeof import('./src/components/ui/redCaution.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    Status: typeof import('./src/components/ui/status.vue')['default']
    SuccessModal: typeof import('./src/components/ui/successModal.vue')['default']
    SucessIcon: typeof import('./src/components/ui/sucessIcon.vue')['default']
    Switch: typeof import('./src/components/ui/switch.vue')['default']
    Tab: typeof import('./src/components/ui/tab.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
