# .github/workflows/release.yml
name: Build & Release Electron App (Windows Only)

on:
  push:
    tags:
      - 'v*' # Trigger only when pushing tags like v1.0.0

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Windows Installer & Publish
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
